---
name: BlockIDStick
main: xtakumatutix\blockids\Main
version: 1.0.5
api: 4.0.0
commands:
  bis:
    description: BlockをタップするとIDなどがわかる棒を出します
    usage: /bis
    permission: "bis.command"

permissions:
  bis.command:
    default: op
...
